### ISSUE TITLE
`Err` value: Unsupported(SamplePrecision(12))'

### ISSUE THREAD

**Issue by pornel** [kaksmet/jpeg-decoder#40]
Unable to decode this image:

![test](https://cloud.githubusercontent.com/assets/72159/16467705/72c6de7c-3e40-11e6-832e-07800a3208a0.jpg)

I think the error is misleading, because the image has 8-bit precision (decodes fine with the default build of libjpeg-turbo).

**Comment by kaksmet** [comment]
That image does indeed have 8-bit precision, but it makes use of 16-bit quantization tables. That combination is explicitly disallowed in the JPEG spec under section B.2.4.1:

>**Pq:** Quantization table element precision – Specifies the precision of the Q<sub>k</sub> values. Value 0 indicates 8-bit Q<sub>k</sub> values; value 1 indicates 16-bit Q<sub>k</sub> values. **Pq shall be zero for 8 bit sample precision P (see B.2.2).**

But since other major JPEG decoders allows this behavior and there are images in the wild utilising it, I'm going to have to add support for it.
