### ISSUE TITLE
Support emscripten targets

### ISSUE THREAD

**Issue by CryZe** [kaksmet/jpeg-decoder#75]
At the moment a worker thread is used while decoding. However the emscripten targets (asm.js and WebAssembly) don't support threads, so a synchronous alternative implementation should be used for those targets. The worker thread could possibly just be executed on the main thread for example.

On a side note: rayon is used in other places, but that works just fine with emscripten targets, so supporting emscripten isn't all too big of a change.

**Comment by kaksmet** [comment]
I wont have time to do this myself, but patches are welcome.

**Comment by gregkatz** [comment]
Hi, in case anyone is still interested in this, I made a quick and dirty fork of this to remove threading to support emscripten (and presumably other web) targets. I'm not submitting a pull request because I wouldn't be able to do it cleanly without adversely affecting non-web targets.

If, like me, you are depending on a crate that depends on jpeg-decoder, you can use my fork by adding the following to your Cargo.toml:

`
[patch.crates-io]
jpeg-decoder = { git = "https://github.com/gregkatz/jpeg-decoder.git", branch = "worker_context" }
`
