### ISSUE TITLE
Decoded data contains imperceptible errors

### ISSUE THREAD

**Issue by tdryer** [kaksmet/jpeg-decoder#91]
Why does [reftest allow a pixel component to be off by 2](https://github.com/kaksmet/jpeg-decoder/blob/07b00818dfb5a45a148ba08188a8fe52ff117b15/tests/reftest/mod.rs#L60) from the reference? Changing it to 0 makes the test fail, indicating the output does not exactly match the reference.

I noticed this because I was trying to check the output of my own program against a reference, but the difference introduced by jpeg-decoder caused it to fail.

**Comment by kaksmet** [comment]
The reference images have been created by decoding the jpegs with libjpeg-turbo and then converting to png.
jpeg-decoder's output can differ slightly from libjpeg-turbo's because the upsampling implementation is not the same. But that is acceptable since the JPEG specification doesn't specify what upsampling algorithm should be used, so implementations are free to do whatever they want.

**Comment by tdryer** [comment]
Thanks for the explanation.
